# Generated by Django 2.2.4 on 2020-02-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0003_visita_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='equipo',
            field=models.CharField(default='Disponible', max_length=20),
        ),
    ]
