# Generated by Django 3.0.3 on 2020-03-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0005_tiempos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempos',
            name='tiempo',
            field=models.IntegerField(default=0),
        ),
    ]
