# Generated by Django 3.0.3 on 2020-03-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0006_auto_20200308_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='episodio',
            field=models.IntegerField(default=0),
        ),
    ]
