# Generated by Django 2.2.5 on 2020-01-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
