# Generated by Django 2.2.4 on 2020-02-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_visita', models.IntegerField()),
                ('id_especialista', models.IntegerField()),
                ('id_paciente', models.IntegerField()),
                ('h_inicio', models.TimeField()),
                ('h_termino', models.TimeField(auto_now_add=True)),
                ('detalle', models.CharField(max_length=400)),
            ],
        ),
    ]
