# Generated by Django 3.0.3 on 2020-02-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fecha', models.IntegerField()),
                ('id_especialista', models.IntegerField()),
                ('detalle', models.CharField(max_length=400)),
            ],
        ),
    ]
