# Generated by Django 2.2.4 on 2020-02-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='id_paciente',
        ),
    ]
