# Generated by Django 3.0.3 on 2020-03-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_remove_formulario_id_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='antecedentes',
            field=models.CharField(default='Vacio', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='comentarios',
            field=models.CharField(default='Vacio', max_length=400),
        ),
        migrations.AddField(
            model_name='formulario',
            name='escala_braden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formulario',
            name='escala_norton',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formulario',
            name='evolucion',
            field=models.CharField(default='Vacio', max_length=400),
        ),
        migrations.AddField(
            model_name='formulario',
            name='indice_barthel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formulario',
            name='pendientes',
            field=models.CharField(default='Vacio', max_length=400),
        ),
        migrations.AddField(
            model_name='formulario',
            name='red_apoyo',
            field=models.CharField(default='Vacio', max_length=20),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='detalle',
            field=models.CharField(default='Vacio', max_length=400),
        ),
    ]
