# Generated by Django 3.0.3 on 2020-03-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0004_formulario_id_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='antecedentes',
            field=models.CharField(default='Vacio', max_length=400),
        ),
    ]
