# Generated by Django 2.2.5 on 2019-11-03 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_remove_especialista_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateReserva',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Visita', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Rut', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.Usuario')),
            ],
        ),
    ]
