# Generated by Django 2.2.5 on 2019-11-06 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datereserva',
            name='timestamp',
        ),
    ]
