# Generated by Django 2.2.5 on 2019-11-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0002_remove_datereserva_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datereserva',
            name='Rut',
            field=models.CharField(max_length=13),
        ),
    ]
