# Generated by Django 2.2.5 on 2019-11-06 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0003_auto_20191106_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datereserva',
            name='Rut',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.Usuario'),
        ),
    ]
