# Generated by Django 2.2.5 on 2019-11-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0004_auto_20191106_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datereserva',
            name='Rut',
            field=models.CharField(max_length=30),
        ),
    ]
