# Generated by Django 2.2.5 on 2019-11-10 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0005_auto_20191109_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='datereserva',
            name='Latitud',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datereserva',
            name='Longitud',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
