# Generated by Django 2.2.5 on 2019-12-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0006_auto_20191110_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datereserva',
            name='Latitud',
        ),
        migrations.RemoveField(
            model_name='datereserva',
            name='Longitud',
        ),
        migrations.AddField(
            model_name='datereserva',
            name='Status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
