# Generated by Django 2.2.5 on 2019-12-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0008_auto_20191202_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datereserva',
            name='Status',
            field=models.IntegerField(default=2),
        ),
    ]
