# Generated by Django 2.2.4 on 2019-10-30 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20191027_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
