# Generated by Django 3.0.3 on 2020-02-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_archivo_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo_Unico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin titulo', max_length=50)),
                ('file', models.FileField(upload_to='archivos/')),
                ('paciente', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
