# Generated by Django 2.2.5 on 2020-02-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tutor', models.IntegerField()),
                ('rut', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=200)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('respuesta', models.CharField(default='Sin Respuesta', max_length=200)),
            ],
        ),
    ]
