# Generated by Django 2.2.5 on 2020-02-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_consulta_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
