# Generated by Django 2.2.5 on 2020-02-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20200206_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='respuesta',
            field=models.IntegerField(default=0),
        ),
    ]
