# Generated by Django 2.2.5 on 2020-02-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20200206_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='respuesta',
            field=models.CharField(default='Sin Respuesta', max_length=200),
        ),
    ]
