# Generated by Django 2.2.5 on 2020-02-06 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_auto_20200206_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='id_usuario',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
