# Generated by Django 2.2.5 on 2020-02-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20200206_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
