# Generated by Django 3.0.3 on 2020-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_auto_20200207_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='mensaje',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='respuesta',
            field=models.CharField(default='Sin Respuesta', max_length=400),
        ),
    ]
