# Generated by Django 3.0.3 on 2020-03-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0004_auto_20200213_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiempos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('tiempo', models.TimeField(blank=True)),
            ],
        ),
    ]
