# Generated by Django 3.0.3 on 2020-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0007_visita_episodio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llamar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=40)),
                ('texto_explicativo', models.CharField(max_length=200)),
            ],
        ),
    ]
