# Generated by Django 3.0.3 on 2020-03-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0005_auto_20200308_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='episodio',
            field=models.IntegerField(default=0),
        ),
    ]
