# Generated by Django 2.2.5 on 2019-10-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191021_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_personales',
            name='idDatosPer',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
