# Generated by Django 2.2.5 on 2019-10-30 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191023_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('datos_personales_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.Datos_Personales')),
                ('Cargo', models.IntegerField(default=2)),
                ('Email', models.CharField(default='', max_length=30)),
                ('Especialidad', models.CharField(default='', max_length=30)),
            ],
            bases=('login.datos_personales',),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Nombre_Completo_Tutor',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Rut_Tutor',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Cargo',
            field=models.IntegerField(default=1),
        ),
    ]
