# Generated by Django 2.2.5 on 2019-10-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191030_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='Especialidad',
        ),
    ]
