# Generated by Django 2.2.5 on 2019-11-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_especialista_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_personales',
            name='Segundo_Nombre',
        ),
    ]
