# Generated by Django 2.2.5 on 2019-11-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_datos_personales_segundo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_personales',
            name='Comuna',
        ),
        migrations.RemoveField(
            model_name='datos_personales',
            name='Domicilio',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Comuna',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Domicilio',
            field=models.CharField(default='', max_length=30),
        ),
    ]
