# Generated by Django 2.2.5 on 2019-11-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20191106_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Domicilio',
            field=models.CharField(default='', max_length=50),
        ),
    ]
