# Generated by Django 2.2.4 on 2019-10-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(default='Sin titulo', max_length=50),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='file',
            field=models.FileField(blank=True, upload_to='archivos/'),
        ),
    ]
