# Generated by Django 2.2.6 on 2019-10-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id_biblioteca', models.IntegerField(primary_key=True, serialize=False)),
                ('contacto_hospital', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id_cuidador', models.IntegerField(primary_key=True, serialize=False)),
                ('parentezco', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Personales',
            fields=[
                ('id_datos_personales', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=15)),
                ('segundo_nombre', models.CharField(max_length=15)),
                ('primer_apellido', models.CharField(max_length=15)),
                ('segundo_apellido', models.CharField(max_length=15)),
                ('domicilio', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=15)),
                ('rut', models.CharField(max_length=15)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('comuna', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.IntegerField(primary_key=True, serialize=False)),
                ('Hora_Inicio', models.TimeField()),
                ('Hora_Fin', models.TimeField()),
                ('fecha_ruta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=100)),
                ('id_datos_personales', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Datos_Personales')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('id_cuidador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ruta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Ruta')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cuidador',
            name='id_usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Datos_Personales'),
        ),
        migrations.CreateModel(
            name='Calendario_Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecah_Calendario', models.DateField()),
                ('id_cuidador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Cuidador')),
            ],
        ),
    ]
