# Generated by Django 2.2.6 on 2019-11-02 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_remove_especialista_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.IntegerField(primary_key=True, serialize=False)),
                ('cant_funcionarios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignar',
            fields=[
                ('equipo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipo.Equipo')),
                ('funcionario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.Especialista')),
            ],
            bases=('equipo.equipo',),
        ),
    ]
