# Generated by Django 2.2.6 on 2019-11-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_especialista_especialidad'),
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crear',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='equipo.Crear')),
                ('Rut', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.Especialista')),
            ],
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
