# Generated by Django 2.2.2 on 2019-12-04 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20191110_1453'),
        ('especialista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='comentario',
            field=models.CharField(default='', max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Usuario'),
        ),
    ]
