# Generated by Django 2.2.2 on 2019-12-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0002_auto_20191203_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='hora',
            field=models.DateTimeField(null=True),
        ),
    ]
